import 'package:optimeal/models/recipe_origin.dart';
import 'package:optimeal/services/ledger_service.dart';

/// Every outcome a completed cook session can produce with respect to the
/// Waste Ledger — see CLAUDE.md, "Waste Ledger legibility — option B"
/// (docs/DECISIONS.md) and Roadmap item 28. Display-only over the existing
/// [LedgerCompletionResult] sealed type and [RecipeOrigin] — neither is
/// modified to support this; both already carry enough information (see
/// [selectLedgerVerdict]'s doc for how each variant is distinguished).
enum LedgerVerdict {
  /// A real waste_ledger_events row exists (fresh insert or an idempotent
  /// retry) and the celebration sheet already renders this — see
  /// [selectLedgerVerdict]'s doc; no separate verdict UI needed for this case.
  counted,

  /// The recipe was not generated by Fridge Clearer (a Custom AI Recipe
  /// Creator craving, the demo, or anything persisted before provenance was
  /// recorded) — `logCompletion` was never called.
  ///
  /// Renamed from `notCountedWrongSurface`: eligibility is a property of the
  /// recipe now, not of the screen the cook was launched from. A Fridge
  /// Clearer recipe cooked out of the Weekly Planner is [counted], and used
  /// to land here wrongly.
  notCountedNotFridgeRecipe,

  /// The cook was a re-cook (Home's Recently Cooked) — `logCompletion` was
  /// never called, regardless of the recipe's origin.
  notCountedReCook,

  /// `logCompletion` was called, the recipe's origin was rescue-eligible,
  /// this was not a re-cook, but the write itself failed
  /// ([LedgerCompletionWriteFailed]) — the attempt is saved by
  /// [PendingLedgerWriteService] and will retry, not lost.
  writeFailedQueued,

  /// The hardcoded local-only demo recipe (no real [CookModeRecipePayload]
  /// at all — reachable via the bare `OnePanCookingRoadmapScreen()` route
  /// fallback in nav.dart when no launch extra is provided). Not a real
  /// cook, not a real rescue attempt — no verdict is shown for this case
  /// at all (see the UI call site); it's still its own enum value so the
  /// selection logic never has to guess or conflate it with a genuine
  /// "wrong surface" outcome.
  demo,
}

/// Picks the [LedgerVerdict] for a completed cook session.
///
/// Distinguishes all 5 outcomes from state the post-cook flow already
/// computes, with no changes to [LedgerService] or [RecipeOrigin]:
/// - [LedgerVerdict.demo]: `hasPayload` is false (this is the only signal
///   that's independent of `origin`/`isReCook` — a demo cook can otherwise
///   present with the same `origin: null` as a legacy recipe).
/// - [LedgerVerdict.notCountedReCook]: `isReCook` is true. Checked before
///   the origin check so a re-cook of a genuine Fridge Clearer recipe is
///   reported as "already counted" rather than as "not a fridge recipe" —
///   both are "not counted", but only one of them is true.
/// - [LedgerVerdict.notCountedNotFridgeRecipe]: `origin` is null (demo, or
///   a recipe persisted before provenance was recorded) or
///   [RecipeOrigin.isRescueEligible] is false.
/// - [LedgerVerdict.writeFailedQueued]: everything above passed (a real
///   rescue-eligible, non-re-cook, non-demo completion), `logCompletion` was
///   called, and it returned [LedgerCompletionWriteFailed].
/// - [LedgerVerdict.counted]: same as above, but [LedgerCompletionSuccess].
///   Note this is reached for a Fridge Clearer recipe **whatever screen
///   launched the cook** — including the Weekly Planner, which is the whole
///   point of keying on origin rather than surface.
///
/// [result] is only meaningful (and only ever non-null in real call sites)
/// when neither [demo] nor a "not counted" case applies — passing a non-null
/// result alongside e.g. `isReCook: true` is not a real call shape, but this
/// function still resolves deterministically (the re-cook check wins) rather
/// than throwing, since it's pure classification logic, not a guard.
LedgerVerdict selectLedgerVerdict({
  required bool hasPayload,
  required bool isReCook,
  required RecipeOrigin? origin,
  required LedgerCompletionResult? result,
}) {
  if (!hasPayload) return LedgerVerdict.demo;
  if (isReCook) return LedgerVerdict.notCountedReCook;
  if (origin == null || !origin.isRescueEligible) {
    return LedgerVerdict.notCountedNotFridgeRecipe;
  }
  if (result is LedgerCompletionSuccess) return LedgerVerdict.counted;
  return LedgerVerdict.writeFailedQueued;
}

/// User-facing verdict copy, exactly one short line per verdict (device-test
/// round F3 — the verdict sheet is one icon, one line, one CTA now, not a
/// multi-line explainer). Plain, warm, non-technical, under 15 words.
/// [LedgerVerdict.counted] has no entry here: the existing celebration
/// sheet already serves as that verdict (CLAUDE.md instruction — keep it,
/// don't duplicate it). [LedgerVerdict.demo] also has no entry: no verdict
/// is shown for it at all.
const Map<LedgerVerdict, String> ledgerVerdictCopy = {
  // Reworded 2026-08-21 to match the approved ledger-explainer ruling. The
  // old line ("This wasn't cooked from your fridge — only Fridge Clearer
  // cooks count.") described launch-surface gating, which stopped being the
  // rule on 2026-08-20: eligibility is a property of the recipe's origin, so
  // a Fridge Clearer recipe counts wherever it is cooked. Only the reason a
  // cook DIDN'T count needed correcting — the counted case has no entry here
  // (the celebration sheet serves it) and its signed one-line structure is
  // untouched.
  LedgerVerdict.notCountedNotFridgeRecipe:
      "Rescues come from Fridge Clearer recipes — this one didn't.",
  LedgerVerdict.notCountedReCook:
      "Already counted the first time you cooked this — re-cooks don't count again.",
  LedgerVerdict.writeFailedQueued:
      "Your rescue is saved and will sync automatically — nothing's lost.",
};
