/// Where a recipe was **generated** — provenance that belongs to the recipe
/// itself, not to whatever screen happened to launch a given cook of it.
///
/// This replaces surface-gated rescue eligibility. The old rule asked "which
/// screen started this cook?", which meant a Fridge Clearer recipe scheduled
/// into the Weekly Planner and cooked from there did **not** count as a
/// rescue — the food was still rescued from the user's fridge, the app just
/// looked at the wrong thing. Provenance now travels with the recipe payload
/// (`CookModeRecipePayload.origin`) and survives every path the recipe takes:
/// straight into Cook Mode, into `user_meal_plans.recipe_payload` jsonb and
/// back out, into the local active-session/history stores, and into
/// `saved_recipes`.
///
/// [CookModeSurface] still exists and is still recorded as launch context,
/// but it no longer decides anything about the Waste Ledger.
enum RecipeOrigin {
  /// Generated by Fridge Clearer from ingredients the user said were in
  /// their fridge. The only rescue-eligible origin.
  fridgeClearer,

  /// Generated by the Custom AI Recipe Creator from a free-text craving.
  /// Never a rescue: nothing here came out of the user's fridge.
  customAiRecipeCreator;

  /// Whether a genuine (non-re-cook) completion of a recipe with this origin
  /// counts as a real ingredient rescue.
  bool get isRescueEligible => this == RecipeOrigin.fridgeClearer;

  /// The `waste_ledger_events.source` value to record. Null for origins that
  /// never log — `logCompletion` is not called for those, so no value is
  /// needed. Kept as `'fridge_clearer'` regardless of launch surface: the
  /// column describes where the recipe came from, which is exactly what this
  /// enum is.
  String? get ledgerSourceValue => switch (this) {
        RecipeOrigin.fridgeClearer => 'fridge_clearer',
        RecipeOrigin.customAiRecipeCreator => null,
      };

  /// Tolerant decode for persisted values. Returns null for null, unknown,
  /// or malformed names rather than throwing — a recipe stored before this
  /// field existed has no origin, and "unknown origin" must degrade to
  /// "not rescue-eligible", never to a guess.
  static RecipeOrigin? fromName(Object? raw) {
    if (raw is RecipeOrigin) return raw;
    final name = raw?.toString().trim();
    if (name == null || name.isEmpty) return null;
    for (final v in RecipeOrigin.values) {
      if (v.name == name) return v;
    }
    return null;
  }
}
