/// Chef Harris Curriculum — Reference Drawers (Bucket B, part 2 of 3)
///
/// Same pattern as chef_curriculum_techniques.dart: each entry is a
/// self-contained plain-text reference block, looked up and injected
/// into the AI prompt only when relevant — not sent on every call.
///
/// Covers: Mise en Place, Food Storage, Cross-Contamination, Knife
/// Mechanics (grip, cuts, safety), and the General Tips & Tricks bank.
///
/// EDITING: Each block is plain text between triple-quotes. Safe to
/// tweak wording or numbers inside any block without touching anything
/// else in this file or any other file in the app.
library chef_curriculum_reference;

const Map<String, String> chefReferenceDrawers = {
  // ---------------------------------------------------------------------
  // MISE EN PLACE, STORAGE & FOOD SAFETY
  // ---------------------------------------------------------------------

  'mise_en_place': '''
TECHNIQUE: Mise en Place (Prep Organization)
RATIOS: Read the full recipe/dish once, top to bottom, BEFORE cutting anything — prevents most mid-cook scrambling. Divide the workspace into three zones: raw prep (cutting board + trim scraps), cooked/ready components (small bowls/ramekins), active cooking (stove/oven adjacent) — never let these overlap. Identify the longest-cooking component first and sequence every other prep task backward from the target serving time. Ideal tool: 4–6 small prep bowls/ramekins minimum; sheet trays for organizing larger batches. No prep bowls? Small cups, jars, or physically separated sections of a large cutting board work.
WORKFLOW: Prep everything that doesn't need last-minute freshness FIRST (aromatics, dense veg, portioned proteins) — save delicate, fast-oxidizing items (herbs, avocado, anything squeezed with citrus) for immediately before use. Use "dead time" (something simmering/resting/in the oven) to prep the next component. Clean as you go — specifically clearing boards and washing knives between raw-protein prep and anything else, which is a direct food-safety control point, not just tidiness.
READINESS CHECKPOINTS: Every component should be visible and accounted for before the first pan goes on heat. Components grouped in the order they'll be used, matching your physical layout to your cooking sequence. Aim to have mise complete with a 5–10 min buffer before active cooking starts — absorbs inevitable small surprises.
PITFALLS: (1) Starting to cook before prep is finished (e.g. burnt garlic while still dicing) — fix: pull the pan off heat entirely to catch up, rather than trying to cook and prep simultaneously under pressure. Note: starting to sweat an onion while prepping something else that goes in later is a smart move IF you know what you're doing and aren't juggling too much. (2) No plan for scraps/trim → clutter, contamination risk — fix: keep a trim bowl/compost container within arm's reach, clear it the moment the board gets crowded. (3) Underestimating prep time → rushed, sloppy work — fix: pad estimated prep time by 25–50%, especially for unfamiliar recipes or knife work you're not yet fast at.
INGREDIENT FLEX: Dense proteins can be portioned/seasoned ahead (dry brining), stored covered and refrigerated. Delicate proteins should be prepped LAST, immediately before cooking — they degrade in texture and food-safety quality fastest. Dense/root veg can be prepped furthest in advance — hold up well, minimal oxidation risk. Leafy/watery veg should be prepped close to cook time; if prepped ahead, store dry and well-wrapped to slow wilting/moisture loss. A divided tray or large sectioned plate can substitute for multiple small bowls when space is limited.
''',

  'food_storage': '''
TECHNIQUE: Food Storage Fundamentals
RATIOS: Refrigerator at or below 4°C/40°F. Freezer at -18°C/0°F or below for long-term stability. Cooling large batches (soups, stocks, stews): 60°C/140°F to 21°C/70°F within 2 hours, then 21°C/70°F to 4°C/40°F within an additional 4 hours — a real food-safety rule, not a suggestion. Shallow containers (max 5–7cm/2–3in depth) cool hot food far faster than a deep pot at the center. Ideal tool: shallow wide containers for cooling; airtight or vacuum-sealed for longer freezer storage (minimizes freezer burn via oxygen exposure). An ice bath under a pot of hot liquid dramatically speeds initial cooling before it even goes in the fridge.
STORAGE CUES: "Danger zone" is 4–60°C/40–140°F — the range where bacteria multiply fastest; the entire storage discipline exists to minimize time spent here. Date everything going into storage — "first in, first out" only works if you can see what's oldest. Raw proteins stored on the LOWEST fridge shelf, below ready-to-eat and produce — prevents drips/leaks from contaminating anything below, and that shelf also runs coldest.
QUALITY & SAFETY CHECKPOINTS: No off-color, no visible mold, no sliminess on proteins — a first-pass visual check, but don't rely on visuals alone. A sour, ammonia-like, or "off" smell is a hard stop — when in doubt, throw it out, no exceptions for food safety calls. General shelf life (refrigerated, cooked): most cooked leftovers good 3–4 days; raw proteins generally used/frozen within 1–2 days (poultry/fish) to 3–5 days (beef/pork) of purchase. Freezer: most proteins hold quality 3–6 months (longer for beef, shorter for fish) — quality (not safety) degrades gradually beyond that from freezer burn.
PITFALLS: (1) Cooling large batches in a deep pot directly in the fridge → lingers in the danger zone too long — fix: transfer to shallow containers immediately, or use an ice bath first. (2) Raw proteins stored above ready-to-eat food → cross-contamination risk from drips — fix: reorganize immediately, proteins on the bottom shelf, always. (3) No labels/dates → food gets forgotten, wasted, or worse, eaten past safety — fix: institute a simple system (masking tape + marker is enough) — a zero-waste discipline as much as a safety one.
INGREDIENT FLEX: Dense proteins freeze well — portion before freezing so you're not thawing more than needed. Delicate proteins (fish/shellfish) have the shortest safe fridge window (often 1–2 days) — buy closer to cook day, or freeze immediately. Dense/root veg is the longest-storing category by far — cool, dark, ventilated storage often suits potatoes/onions better than the fridge. Leafy/watery veg has the shortest produce shelf life — store dry, loosely wrapped, use within a few days. Reused glass jars work as well as purpose-bought containers for most storage needs, and support the zero-waste ethos directly.
''',

  'cross_contamination': '''
TECHNIQUE: Cross-Contamination Prevention
RATIOS: Minimum two cutting boards in active rotation — one dedicated to raw proteins, one for produce/ready-to-eat (color-coded boards make this foolproof). Handwashing: minimum 20 seconds with soap, specifically before AND after handling raw proteins — a hard non-negotiable checkpoint. Ideal tool: color-coded cutting boards (commonly red for raw meat, green for produce) and separate utensils/tongs for raw vs. cooked proteins. A single board can work if thoroughly washed with hot soapy water between raw-protein and produce use, but dedicated boards remove the risk of forgetting that step under time pressure.
WORKFLOW: Always prep produce/ready-to-eat items BEFORE raw proteins when sharing tools/boards, never after — minimizes the contamination window even if you forget to wash between steps. Any spoon, tongs, or plate that touched raw protein must not touch cooked/finished food without being washed first ("the tongs that put it on the grill can't take it off" unless washed between).
SAFETY CHECKPOINTS: Distinct, dedicated tools/boards clearly in use and not swapped mid-task. Wash hands until you can no longer feel any residue/oil film from raw protein handling. Treat any pause in raw-protein handling (even a short one) as a trigger to wash hands before touching anything else — phones, drawer handles, seasoning containers included.
PITFALLS: (1) Using the same plate for raw and cooked protein (classic grilling mistake) — fix: do not serve as-is, fully re-cook or discard the contaminated portion, there's no "wipe it off" fix. (2) Marinade used on raw protein then reused as a finishing sauce without boiling — fix: bring any reused marinade to a full boil for at least 1 minute first to neutralize bacterial contamination. (3) Forgetting to wash hands between raw protein and other ingredients/tools — fix: wash the moment you notice, treat it as habit-building, not just a one-off fix.
INGREDIENT FLEX: Applies universally across all ingredient categories — the discipline doesn't change based on what's being prepped, only the specific risk level shifts (raw poultry generally carries the highest cross-contamination concern of common proteins). Disposable cutting sheets are a lightweight alternative to a second board for small households or tight kitchens, discarded after raw-protein use.
''',

  // ---------------------------------------------------------------------
  // KNIFE MECHANICS & PREP
  // ---------------------------------------------------------------------

  'knife_grip_mechanics': '''
TECHNIQUE: Knife Grip & Body Mechanics
RATIOS: Pinch grip — thumb and index finger pinching the blade itself just above the bolster, remaining three fingers wrapped around the handle. Non-negotiable; a full-handle "hammer grip" sacrifices control. Guide hand: "claw grip" — fingertips curled under, knuckles forward and vertical, acting as a flat guide wall for the blade; thumb tucked behind the other fingers. The blade rides against the knuckle, never past it. Damp paper towel or non-slip mat under the board — zero board movement is the target. Ideal tool: 20cm/8in chef's knife as the primary workhorse (covers ~80% of prep); paring knife (9–10cm) for small precision work; serrated knife for bread/delicate skins. A santoku is a reasonable chef's-knife substitute for smaller hands or a rocking-motion preference.
BLADE & BOARD CUES: The blade should glide through a tomato skin under its own weight, no sawing/pressing required — resistance means it's time to hone or sharpen. Board should sit dead still under moderate pressure — any sliding is a safety fail, fix it before continuing. Proper cutting motion is a forward rocking glide (tip stays largely in contact with the board), not an up-and-down chopping hack.
CUT QUALITY CHECKPOINTS: Uniform cut sizes across a batch — affects downstream cook-time evenness more than most home cooks realize. Guide-hand knuckles should feel the blade lightly brushing with every cut — that contact is what keeps fingertips safely tucked. Always cut the flattest, most stable side of an ingredient first to create a stable base (e.g. slice a small flat off a round onion or potato before cutting further).
PITFALLS: (1) Curled fingers not tucked (claw grip abandoned) → nicked fingertips — fix: stop immediately, reset guide hand into proper claw position before continuing. (2) Dull knife, forcing/sawing through food → slips and injuries — fix: hone with a honing steel before every session; a dull knife is more dangerous than a sharp one because it needs more force and less control. (3) Unstable board (wobbling/sliding) → loss of control mid-cut — fix: stop, place a damp towel or non-slip mat underneath immediately.
INGREDIENT FLEX: Dense proteins use a boning/fillet knife for breaking down whole cuts (flexible blade follows bone/joint lines); chef's knife handles slicing cooked/portioned dense proteins. Delicate proteins: a flexible fillet knife for fish; a very sharp chef's knife for clean egg/tofu cuts (dull blades crush tofu instead of slicing). Dense/root veg: chef's knife with real downward pressure and a stable rocking motion; a mandoline (with guard, always) for uniform thin slices at volume. Leafy/watery veg: chef's knife with a light touch — bruise/oxidize faster under a dull or aggressive blade.
''',

  'core_knife_cuts': '''
TECHNIQUE: Core Knife Cuts
CUT SPECS: Julienne 3mm x 3mm x 5cm (matchstick) — the building block for brunoise, and a classic garnish/quick-cook cut. Brunoise: julienne turned 90° and diced to a fine 3mm cube, used for aromatics needing to "melt" into a dish. Small dice: 6mm cube. Medium dice: 1.25cm cube. Large dice: 2cm cube — the standard escalating dice family, chosen by cook time and dish style. Chiffonade: thin ribbon cuts (1–3mm wide) of leafy herbs/greens, made by stacking, rolling tightly, then slicing across the roll. Rondelle/bias cuts: straight or angled coin-shaped slices of cylindrical vegetables (carrots, cucumbers), thickness typically 3–6mm. Ideal tool: chef's knife for all of the above; a ruler genuinely helps calibrate the eye during the first few practice sessions.
BLADE & BOARD CUES: Line up finished cuts against each other — visible size variance beyond ~1mm across a batch means slow down and tighten up. Brunoise/julienne work best with a full, controlled rocking stroke using the whole blade length, not just the tip. Keep a "work zone" (cutting) separate from a "holding zone" (finished cuts pushed to the side).
CUT QUALITY CHECKPOINTS: Clean, sharp edges on every piece — a properly sharp knife produces crisp corners, not crushed or torn edges. Pieces should stack and sit flat/uniform when piled — a strong sign of consistent sizing. Cut aromatics for a long braise/stock larger (rough chop, since they cook down); cut aromatics for a quick sauté/garnish smaller (fine dice/brunoise) since they need to cook through fast.
PITFALLS: (1) Inconsistent sizing → uneven cook times — fix: for the current batch, sort pieces by size and stagger their addition to the pan (larger first). (2) Crushed/bruised cuts (especially herbs, tomatoes) from a dull blade — fix: re-sharpen/hone before continuing; a bruised cut also oxidizes and browns faster. (3) Rushing a fine dice and losing consistency — fix: slow the tempo down, prioritize accuracy over speed — speed comes with repetition, it can't be forced early on.
INGREDIENT FLEX: Dense proteins are always cut against the grain for tenderness — direction relative to muscle fiber matters more than the size spec. Delicate proteins need minimal handling, a very sharp blade, single clean strokes rather than sawing. Dense/root veg: stable base cut first (flatten one side), then proceed to the target size — most home cooks skip this and compromise safety. Leafy/watery veg: chiffonade for herbs/leafy greens; larger dice for watery vegetables (zucchini, mushrooms) since they shrink significantly during cooking. Kitchen shears are a legitimate substitute for chiffonade-style herb cuts if knife confidence is still developing.
''',

  'knife_safety_protocol': '''
TECHNIQUE: Knife Safety Protocol
SAFETY SPECS: Store knives blade-down in a block, on a magnetic strip, or in individual sheaths — never loose in a drawer with other utensils. Carry with blade pointed down, held flush against the leg, calling out "behind" or "corner" when passing others. Hand-wash immediately after use, blade facing away from your hand, never left submerged in a sink where it can't be seen. Ideal tool: a stable, appropriately-sized cutting board (large enough food doesn't hang off the edge) is itself a core safety tool.
BLADE & BOARD CUES: Before the first cut of any session, confirm: board is stable, workspace is clear of clutter, guide hand is in claw position. If grip or focus starts slipping (common after repetitive cutting), that's the signal to pause, not push through — most kitchen cuts happen in the final few reps of a task, not the first.
SAFETY CHECKPOINTS: Guide hand knuckles ahead of fingertips at all times, blade never crosses that knuckle line. A comfortable, un-strained grip — white-knuckling the handle is a sign of poor grip mechanics, not focus. Knife goes down flat on the board any time it's not actively in hand — never left balanced on its edge or propped against something.
PITFALLS: (1) Reaching into a sink to "feel" for a submerged knife → serious cut risk — fix: never submerge knives; if it happens, always visually locate and remove it blade-first with full attention. (2) Cutting toward the guide hand instead of away/parallel — fix: stop, reposition guide hand into proper claw grip before any further cuts. (3) Using a dull knife "because sharpening takes too long" — fix: this isn't a mid-task fix, build a standing habit of honing before every session and professional sharpening every few months.
INGREDIENT FLEX: Applies universally across all ingredient categories — safety protocol doesn't change based on what's being cut, only blade choice and cut size do. A cut-resistant glove is a reasonable aid for beginners or particularly awkward ingredients (whole squash, slippery proteins), without replacing proper technique.
''',

  // ---------------------------------------------------------------------
  // GENERAL CHEF TIPS & TRICKS (curated tip bank, non-matrix format)
  // ---------------------------------------------------------------------

  'general_tips': '''
GENERAL CHEF TIPS & TRICKS (Kitchen Intuition Bank)

SEASONING & TASTING DISCIPLINE: Taste constantly, with intent — raw ingredients before cooking, at each major stage, and again right before plating. A dish seasoned only once, at the end, is a dish seasoned by guesswork. Salt in layers, not in one dump — a little at the start (aromatics), a little during (protein/veg as it cooks), a final check at the end. The mental "flavor equation" is salt, fat, acid, heat (spice), sweetness — if a dish tastes flat but you can't pinpoint why, it's almost always missing one of these five, with acid and salt the two most commonly under-used by home cooks. When a dish tastes flat, reach for acid before reaching for more salt — a squeeze of lemon or splash of vinegar often "wakes up" a dish that would otherwise get over-salted trying to fix it. Underseasoning while cooking is easy to fix; overseasoning is not — season conservatively in stages, especially with ingredients that concentrate (reductions, long braises).

HEAT & PAN INTUITION: A cold pan is the #1 cause of a bad sear, stir-fry, or sauté — preheat the pan itself (empty, dry) for a minute or two before oil ever goes in. Listen to the pan more than watch the clock — sizzle volume and rhythm tell you far more about real-time pan temperature than a timer; a quieting sizzle usually means moisture is cooking off and food is progressing toward done. If in doubt, don't crowd it — across nearly every technique in this curriculum, overcrowding is the single most common root cause of disappointing results. Let food release itself from the pan — if something's sticking hard when you try to flip it, it almost always means it isn't ready yet, not that the pan or oil failed. Preheat ovens fully, always — starting food in an under-temp oven throws off browning and timing for the entire cook.

ZERO-WASTE & INGREDIENT MAXIMIZATION (Chef Harris's signature angle): Vegetable scraps (onion skins, carrot tops, celery ends, herb stems) are stock ingredients, not trash — keep a freezer bag going, and once full it's a free stock batch. Wilting vegetables are a flavor-building opportunity, not a write-off — slightly soft carrots, celery, or peppers are perfect for a sweated aromatic base or a soup, since texture matters less once cooked down anyway. Stale bread has a second life: croutons, breadcrumbs, meatballs, panzanella, or a soup thickener. Buttermilk/dairy nearing its date is a marinade, not a discard — slightly soured dairy is often MORE useful as a tenderizing marinade base than fresh. Herb stems (cilantro, parsley) carry real flavor, especially in a blended sauce, pesto, or stock — chop finely and use as leaves rather than stripping and discarding by habit. Overripe fruit is a dessert or sauce ingredient waiting to happen (compotes, quick jams, blended into a vinaigrette for natural sweetness) rather than a compost-bin default. A weekly "use it up" cook built entirely around whatever's closest to expiration is a genuine professional-kitchen habit (family/staff meal often works this way).

TEXTURE & DONENESS INTUITION: Resistance to touch is one of the most reliable, universal doneness cues across proteins — raw is soft/yielding, well-done is firm, everything else is in between; build this instinct by comparing touch to a thermometer reading until it becomes second nature. Carryover cooking is real — pull proteins slightly before target temperature, residual heat keeps cooking for several minutes, especially for larger cuts. Rest proteins before cutting, without exception for anything larger than a single portion — cutting immediately releases juices onto the board instead of letting them redistribute. A recipe's stated cook time is a guideline, not a guarantee — pan thickness, stove strength, ingredient size, and starting temperature all shift real cook time; always cook to the visual/tactile/thermometer cue, not the clock. When texture is uncertain, cut into or press a piece to check — don't guess from the outside alone, especially with unfamiliar cuts or new-to-you recipes.

EFFICIENCY & KITCHEN WORKFLOW: Clean as you go — a workflow tool, not just tidiness; a clear board and empty sink mid-cook keeps your mind and hands free for the decisions that matter. Read the full recipe before starting, every time, even ones you've made before — missing a step you should've prepped 20 minutes ago is one of the most common, avoidable kitchen stress spirals. Keep a "flavor bombs" shelf stocked — good stock, a sharp vinegar, a favorite hot sauce, good salt, an umami booster (soy, fish sauce, parmesan rind) — these fix more last-minute flavor problems than any technique adjustment can. Batch-cook aromatics/bases when already in the kitchen — a double batch of caramelized onions or a big pot of stock takes barely more active time than a single batch, and freezes well. Sharpen/hone your knife on a schedule, not "when it feels dull" — a dull knife creeps up gradually enough that most cooks don't notice until it's already a safety and quality issue.

RECOVERY & PROBLEM-SOLVING (when it's going wrong): Too salty — add a starchy, unsalted bulk element (extra rice, potato, unsalted stock/water) to dilute, or a touch of acid/sweetness to help balance perception; there's no true "removal," only dilution and balance. Too spicy — dairy (yogurt, cream, coconut milk) neutralizes capsaicin far better than water; a touch of sugar or acid also helps balance the perception of heat. Too acidic — a small amount of fat (butter, cream, oil) or sweetness rounds out sharp acidity, added gradually while tasting. Broken sauce/emulsion — pull off heat immediately, whisk in a splash of cold liquid (water, cream, or an ice cube) off-heat to try to re-establish it before adding more fat. Burnt bottom layer (rice, sauce, braise) — do NOT scrape the burnt layer into the rest of the dish; gently transfer the unburnt portion to a fresh pot/pan, leaving the scorched layer behind entirely. Overcooked/dry protein — slice thin against the grain and serve with a sauce or jus to reintroduce moisture; it won't undo the overcooking, but it meaningfully improves the eating experience.

THE FIVE UNIVERSAL CHEF INSTINCTS (quick reference): (1) Taste at every stage — seasoning is built in layers, not fixed once at the end. (2) Don't crowd the pan/oven/grill — the single most common root cause of poor browning/texture across all techniques. (3) Preheat before food goes in — cold starting surfaces cause sticking, steaming, and uneven cooking. (4) Rest proteins, trust carryover — pulling slightly early and resting locks in juiciness and hits true target doneness. (5) Scraps and near-spoiled food are ingredients — the zero-waste mindset is a flavor-building habit, not a limitation.
''',
};