/// Chef Harris Curriculum — Technique Drawers (Bucket B, part 1 of 3)
///
/// Each entry is a self-contained, plain-text technical reference for one
/// cooking technique: ratios, heat cues, doneness checkpoints, common
/// pitfalls + fixes, and ingredient substitution flex.
///
/// HOW THIS FILE IS USED:
/// The app looks up the relevant technique(s) for a given recipe/chat
/// request and injects the matching text block(s) into the AI prompt —
/// full technical depth, but only for the technique(s) actually in play.
/// This file is NOT injected wholesale into every call.
///
/// EDITING: Each block is plain text. You can safely edit the wording,
/// fix a number, or add a line inside any block below without touching
/// any other part of this file or any other file in the app.
library chef_curriculum_techniques;

const Map<String, String> chefTechniqueDrawers = {
  // ---------------------------------------------------------------------
  // PAN TECHNIQUES — CORE FOUR
  // ---------------------------------------------------------------------

  'stir_frying': '''
TECHNIQUE: Stir-Frying
RATIOS: 1–2 tbsp oil per 2 cups (450g) cut ingredients. Max 50% of wok surface filled per batch. Standard plate: 30% protein / 60% veg / 10% aromatics (plant-forward: 20/70/10). Sauce: 3 tbsp per 2 cups finished stir-fry. Cornstarch slurry if thickening: 1 tsp starch : 2 tbsp cold liquid, added off direct flame. Equipment: carbon steel or cast iron wok, 30–35cm, sloped sides; widest/shallowest skillet as flat-pan substitute.
HEAT: Target 200–230°C/400–450°F, oil shimmering and moving, faint smoke wisp. Wok must be pre-heated dry (30–60 sec) BEFORE oil goes in. Cold food dumped in a mass drops pan temp instantly — batch it: protein first (remove, rest), then vegetables hardest-to-softest. Audio cue: aggressive continuous sizzle-roar on contact; silence = pan wasn't hot enough. Visual: steam should shoot up and dissipate fast — lingering/pooling steam means overcrowded, pull half the batch.
DONENESS: Proteins hit light golden edge in under 90 sec/side before vegetables even start. Vegetables should brighten/intensify in color (broccoli → emerald, not olive) — that's the doneness flag, not softness. Vegetables should retain bite (fork meets slight resistance, never mush). Salt proteins before the pan. Aromatics (garlic/ginger/chili) in for 10–15 sec max, pushed to the side, never dumped into cold oil. Sauce in last, tossed 20–30 sec to glaze not simmer. Acid/herbs added off-heat at the very end.
PITFALLS: (1) Overcrowding → steamed/gray/watery — fix: pull half onto a plate, finish in batches, recombine. (2) Burnt garlic → bitter dish — fix: pull pan off heat immediately, add liquid/sauce to stop cooking. (3) Sauce added too early → sticky glue — fix: splash in hot water/stock to loosen.
INGREDIENT FLEX: Dense proteins sliced against grain, 5mm max thickness; tofu pressed + cornstarch-dusted for crisp shell. Delicate proteins (shrimp, thin fish) go last, 60–90 sec only. Dense/root veg (carrots, broccoli, potatoes) par-cook first — cut broccoli/carrot smaller instead if skipping par-cook. Leafy/watery veg (spinach, tomatoes) added last, 30–60 sec. Oil needs high smoke point (200°C+): peanut, refined avocado, grapeseed, refined sunflower — avoid EVOO and unrefined sesame as the cooking fat (sesame is a finishing drizzle only). Harder veg go in first, softer veg added a few seconds later so the pan stays hot throughout — never dump everything in at once.
''',

  'sauteing': '''
TECHNIQUE: Sautéing
RATIOS: 1–2 tbsp oil per pan (thin ~1mm film). Single layer only, max 70% pan coverage. Aromatics-to-base for a pan sauce build: 1 part minced aromatic : 8–10 parts main ingredient. Deglaze: ¼–½ cup liquid per pan. Equipment: stainless/clad pan for fond development, or nonstick for delicate items; low-to-moderate walls (5–7cm).
HEAT: Target 160–190°C/325–375°F, medium to medium-high, oil shimmers/moves loosely, no smoke yet. Pan and oil must both be hot before food enters. More forgiving of crowding than stir-fry, but still drop pan temp if overcrowded — leave visible gaps. Audio: steady moderate sizzle (not aggressive roar, not silent). Visual: light gentle steam wisps at edges, not billowing.
DONENESS: Even golden-brown Maillard crust over 2–4 min/side — don't move the food, let the crust form. Proteins firm up with gentle resistance; vegetables soften but keep structure. Fond should be deep amber, not black (black = bitter pan sauce). Salt just before the pan for a crust, or partway for gentler proteins like fish. Aromatics go in after main protein/veg has color, so they don't scorch. Finish acid (lemon/vinegar) deglazed into the fond builds the pan sauce.
PITFALLS: (1) Not moving/stirring (sauté = "jump") — technique is defined by medium-high heat + continuous motion, not color; leave it a few seconds for color, then stir. (2) Pan too cool → gray/sweaty food — fix: pull food, crank heat 60 sec, return in batches. (3) Burnt fond ruins pan sauce — fix: wipe pan, fresh oil, build sauce separately. (4) Wet food into oil → violent spatter — fix: pat fully dry or dredge in flour first; always move food away from your body, never toward it.
INGREDIENT FLEX: Dense proteins (chicken breast/pork chops/steak) pat bone-dry first — non-negotiable for crust. Delicate proteins (fish, eggs) at slightly lower heat (medium), nonstick preferred, minimal handling. Dense/root veg slice thin (3–5mm) or par-cook. Leafy/watery veg (mushrooms, zucchini) sauté dry-ish first to drive off water before adding fat. Oil for 175–200°C range: butter (watch burning past 150°C, or use clarified/ghee for higher heat), olive oil, avocado oil, refined sunflower.
''',

  'shallow_frying': '''
TECHNIQUE: Shallow Frying (Pan Frying)
RATIOS: Oil ⅓–½ up the side of the food (1–2cm depth). Max 50% of oil surface occupied at once. Breading: flour → egg wash → breadcrumb, in that fixed order, each layer fully coating before the next. Equipment: heavy-bottomed skillet/straight-sided sauté pan, walls 5cm+ to contain oil.
HEAT: Target 160–180°C/325–350°F — test with a wooden chopstick/bread cube: energetic but not violent bubbling. Oil temp drops 10–15°C the instant food is added (expected — preheat slightly above target, never crowd). Audio: steady rolling bubble/crackle (roaring = too hot, near-silence = too cool). Visual: oil glassy and actively rippling; smoke = past the safe window, pull off heat.
DONENESS: Deep even golden-brown across the whole surface — patchy pale spots mean inconsistent oil contact (crowded or not fully submerged). Crust should sound/feel crisp-hollow when tapped. Internal thermometer for breaded proteins is the real doneness proof (poultry 74°C/165°F, pork/beef 63°C/145°F, minced meat 72°C). Salt the moment food comes out while still hot. Finish with a bright acid side (lemon, vinegar slaw) — never on the crust directly.
PITFALLS: (1) Soggy crust (oil too cool or food added wet) — fix: pull food, raise heat, let oil recover 1–2 min, pat dry before returning. (2) Breading falls off (skipped layer or over-pressed) — fix: press coating back on gently for the current batch; ensure each layer is dry next time. (3) Uneven browning (overcrowded) — fix: remove excess, finish in a second batch, rest on a wire rack (not paper towels beyond 30–60 sec, or the bottom steams soft).
INGREDIENT FLEX: Dense proteins (chicken cutlets/pork chops) pound to even 1–1.5cm thickness first. Delicate proteins (fish) use a lighter dredge and shorter fry time. Dense/root veg (potatoes) par-cook first. Leafy/watery veg (zucchini, mushrooms) salt and drain 10 min before breading. Oil needs stable 180°C+: refined vegetable, canola, peanut, refined sunflower — avoid unrefined/cold-pressed oils, they break down and turn bitter.
''',

  'deep_frying': '''
TECHNIQUE: Deep Frying
RATIOS: Food fully submerged, 5cm/2in clearance above oil to pot rim. Never fill pot more than 50–60% with oil before food goes in. Batch size never exceeds 30% of oil volume at once. Tempura-style batter: 1 part flour : 1 part ice-cold liquid, mixed minimally (lumps fine — gluten is the enemy). Equipment: heavy-bottomed pot/dedicated fryer, tall straight sides, thermometer clipped to the side — not optional for this technique.
HEAT: Target 175–190°C/350–375°F depending on food (lower for thick/raw items, higher for quick-cook/pre-cooked). Oil drops 15–25°C the moment food is added — always preheat 10–15°C above target to compensate. Overcrowding is the #1 cause of greasy deep-fried food, full stop. Audio: vigorous continuous bubbling roar on contact (quiet = oil not hot enough, food absorbs oil instead of frying). Visual: small-to-medium vigorous bubbles, oil clear and mobile; large lazy bubbles = too cool, thin bluish smoke = too hot, pull off heat immediately.
DONENESS: Deep even golden-brown across the entire surface is the primary external cue. Sizzle noticeably quiets as moisture cooks out — a genuine doneness signal. Thermometer mandatory for anything raw inside (poultry 74°C/165°F). Batter-only items (donuts, fritters) rely on color + float test (most float once mostly cooked). Salt immediately on removal onto a wire rack/paper-lined tray. Serve with an acid-forward dip/side — never season the fried item with liquid acid directly.
PITFALLS: (1) Overcrowding → greasy/soggy/undercooked — fix: remove excess, let oil temp fully recover before continuing. (2) Oil too cool at start → everything absorbs oil like a sponge — no fix for that batch, raise temp for the next. (3) Wet food into oil → violent spatter — fix: pat dry/dredge before frying, lower food slowly with a spider/slotted spoon. (4) Never pour hot oil into the sink — let it cool, strain, store in a lidded glass container; reuse if color/smell are unchanged, otherwise find a recycling point.
INGREDIENT FLEX: Dense proteins (bone-in chicken needs lower temp/longer time, 160–165°C); firm tofu cubes cut uniformly. Delicate proteins (fish, shrimp) battered thin, fried hot and fast (185–190°C), pulled the moment color sets. Dense/root veg (potatoes): double-fry method — blanch at 150°C, rest, crisp at 185°C. Leafy/watery veg (mushrooms, zucchini) battered thickly to shield high water content, fried in small batches. Oil needs very stable 190°C+, neutral flavor, large volume: refined peanut, canola, refined vegetable, refined sunflower — never EVOO, unrefined sesame, or flax.
''',

  // ---------------------------------------------------------------------
  // SEARING & SAUCE SCIENCE
  // ---------------------------------------------------------------------

  'pan_searing': '''
TECHNIQUE: Pan Searing
RATIOS: 1–2 tsp high-smoke-point oil — just enough to prevent sticking, the pan's own heat does the work. Food should touch the pan directly across 100% of its surface — pat fully dry first, salt right before it hits the pan. Butter-baste finish: 1–2 tbsp butter + aromatics (garlic, thyme) per portion, added in the last 1–2 min only. Ideal tool: heavy stainless steel or cast iron (builds fond); avoid nonstick for a true sear. Carbon steel works as well as cast iron once seasoned; thin aluminum struggles to hold searing temps.
HEAT: Target 220–240°C/425–460°F pan surface — visibly shimmering, oil moving loosely, just short of smoking. Pan must be fully preheated (2–3 min empty) until a water droplet dances on contact, THEN add oil for another 30–60 sec before food — rushing this is the #1 cause of a weak sear. Food needs space to release its own steam — overcrowding traps moisture and gives gray, boiled-looking edges. Audio: immediate aggressive sizzle on contact; no sound = pan wasn't hot enough. Visual: don't touch/move food for the first 2–3 min — a proper crust releases itself naturally.
DONENESS: Deep even mahogany-brown crust — non-negotiable, that's the Maillard reaction doing its job. Firm, slightly springy resistance when pressed; crust should feel dry and slightly crisp, not tacky. Thermometer for anything thick — pull 3–5°C/5–10°F before target for carryover. Salt generously right before the pan (not hours ahead unless dry-brining). Pan sauce (see below) lives in this same pan, off the fond.
PITFALLS: (1) Moving/flipping too early → torn, pale, sticking — fix: leave it alone, it releases on its own once the crust sets. (2) Wet food from the fridge/marinade → steams instead of sears — fix: pat aggressively dry immediately before the pan, every time. (3) Pan not hot enough → pale, greasy — fix: pull food, reheat properly, don't return until a confident sizzle. (4) Placing protein toward yourself risks an oil splash — always place it away from your body, gently.
INGREDIENT FLEX: Dense proteins (steak, chops, firm tofu) — this technique's home turf; thick cuts benefit from sear-then-oven finish. Delicate proteins (fish fillets skin-on — cook ~80% on the skin side, flip only for the last seconds; scallops) need slightly less heat (200–220°C) and very dry surfaces. Dense/root veg not a primary use case — works better on cut, flat-surfaced pieces than whole roots. Mushrooms sear beautifully (high heat drives off water fast, then browns) — don't crowd them. Oil needs 220°C+: refined avocado, refined grapeseed, clarified butter/ghee — butter alone burns before target temp, use it only for the finishing baste.
''',

  'quick_pan_sauce': '''
CONCEPT: Quick Pan Sauce Logic
RATIOS: Five-part sequence every time — Fond + Deglaze Liquid + Aromatic + Fat + Acid. Deglaze: ¼–½ cup liquid (wine, stock, or a mix) per pan, enough to lift all the fond. Reduce by roughly half before mounting with fat. Fat-mount: 1–2 tbsp cold butter per ¼–½ cup finished sauce, off heat, swirled in ("monter au beurre"). Ideal tool: the exact same pan used to sear/sauté — the fond IS the sauce base, never wash it out.
HEAT: Pan should be hot but off direct high heat when liquid is added — screaming hot pan + liquid causes violent, dangerous splatter. Reduce at a steady simmer, not a rolling boil, or you'll scorch the fond flavor. Sequence matters: deglaze first (loosen fond), reduce second (concentrate), mount third (enrich with fat off heat) — out of order breaks the sauce.
DONENESS: Sauce goes from thin/translucent to glossy, coating-the-back-of-a-spoon consistency. A finger swiped through a spoon dip should leave a clean line that doesn't fill back in. Taste and adjust salt AFTER reducing, never before — reduction concentrates salt significantly. A final splash of fresh acid at the very end wakes up a sauce gone flat from reduction — always taste and adjust here.
PITFALLS: (1) Scorched (black, not brown) fond → bitter sauce no matter what's added — fix: don't deglaze black fond, wipe the pan and start fresh in new fat. (2) Boiling after the butter mount → sauce breaks/separates — fix: pull off heat immediately, whisk in a splash of cold liquid to try to bring it back. (3) Under-reduced, watery sauce — fix: return to heat and simmer more before mounting fat, don't try to fix thinness with more butter (turns greasy).
INGREDIENT FLEX: Dense proteins (pan-seared steak/chicken/pork) — classic pairing, built immediately after the protein rests. Delicate proteins (fish) — lighter hand on reduction time and acid, brighter/less heavy sauces. Root veg finished with a quick drizzle rather than dressed separately. Sautéed mushrooms/greens can be deglazed in the same pan for a one-pan finish. Liquid substitution: white/red wine, stock (any protein), beer, or a splash of vinegar-water mix if nothing else is on hand.
''',

  'emulsified_reductions': '''
CONCEPT: Emulsified Reductions
RATIOS: Classic beurre blanc-style — reduce acid + aromatic (wine/vinegar + shallot) by ~90%, then mount with cold butter off heat, roughly 4–8 tbsp per ¼ cup reduced base. Add fat gradually, a tablespoon/small cube at a time, whisking continuously — dumping all the fat in at once is the #1 cause of a broken sauce. Ideal tool: a small, heavy saucepan (not the searing pan, too hot for this stage).
HEAT: Very low heat, sometimes off heat entirely between butter additions — the lowest-heat-tolerance sauce technique in the kitchen. Held together through constant motion and controlled temperature — too hot and the fat separates out (breaks); too cold and butter won't incorporate. Don't add butter faster than the whisk can incorporate it — patience is the entire technique.
DONENESS: Pale, opaque, uniformly creamy — cohesive and glossy, never oily or separated on the surface. Should coat a spoon smoothly and hold that coating without pooling for a minute. Season the reduction base before mounting fat, then taste again at the end (butter mutes salt perception). Acid is built into the reduction stage here, not added at the end — different from the pan-sauce logic above.
PITFALLS: (1) Sauce breaks (greasy look, oil pooling) — fix: immediately whisk in 1 tbsp cold water or cream off heat to re-establish it. (2) Butter added too fast, doesn't incorporate — fix: slow down, whisk constantly, don't add the next piece until the current one melts in. (3) Held too long over heat → breaks from overheating — fix: hold off heat or on the lowest possible warm setting, use within 20–30 min.
INGREDIENT FLEX: Pairs classically with fish and poultry more than red meat, though a red-wine reduction with a butter mount works with steak too. THE classic sauce category for fish (beurre blanc originated as a fish sauce) — light, rich, acid-balanced. Drizzle over steamed/blanched vegetables (asparagus, green beans) as an elegant finish. Heavy cream can stabilize an emulsion alongside or instead of butter for a more forgiving, less break-prone version, at the cost of some richness/gloss.
''',

  'starch_binding': '''
CONCEPT: Starch Binding (Thickening Logic)
RATIOS: Cornstarch slurry: 1 tsp starch : 2 tbsp cold liquid, whisked smooth before adding to hot liquid — always mix with cold liquid first, never add powder directly to a hot pan. Flour roux: 1:1 fat to flour by weight, cooked 2–5 min before adding liquid (longer cook = deeper color, slightly less thickening power). Beurre manié (quick alternative): equal parts softened butter and flour, kneaded together, whisked into a simmering liquid in small pieces at the end. Reduction can thicken with no starch if you have time — just slower. Ideal tool: a whisk is mandatory — lumps form fast without constant agitation.
HEAT: Liquid should be at a simmer (not a hard boil) when starch slurry is added, then briefly back to a simmer to activate thickening. Cornstarch thickens fully within 30–60 sec of reaching a simmer — don't overcook, prolonged high heat can break down starch and thin the sauce back out. For roux: fat must be hot before flour is added, then liquid added gradually while whisking, ideally off the highest heat to avoid lumps.
DONENESS: Cornstarch-thickened sauces turn glossy and slightly translucent; roux-based sauces range pale (light roux, subtle thickening) to deep brown (dark roux, nutty flavor, less thickening power). "Nappé" test across all methods: sauce coats the back of a spoon and holds a line when a finger drags through it. Season the base liquid before thickening when possible. Add acid after thickening is complete — acid can interfere with starch's thickening ability if added too early in high concentration.
PITFALLS: (1) Lumpy sauce from adding starch/flour directly to hot liquid — fix: strain through a fine mesh sieve. (2) Sauce thins out again after thickening (cornstarch breakdown from overcooking or acid) — fix: mix a fresh small slurry, re-add, brief simmer. (3) Roux undercooked → raw flour taste — fix: nothing recovers this after liquid is added; next time cook the roux until it smells toasty, not raw.
INGREDIENT FLEX: Cornstarch for glossy, clear Asian-style sauces and stir-fry glazes; roux for classic Western sauces (béchamel, gravy) where opacity/body are wanted; beurre manié for a fast mid-cook fix without a separate roux step. Gluten-free: cornstarch, arrowroot, or rice flour — arrowroot gives the glossiest finish and thickens at a lower temp than cornstarch. No fine mesh sieve? A clean tightly-woven cloth or coffee filter works for small amounts.
''',

  // ---------------------------------------------------------------------
  // WATER-BASED TECHNIQUES
  // ---------------------------------------------------------------------

  'boiling': '''
TECHNIQUE: Boiling
RATIOS: Enough water to fully submerge food with 5cm/2in headroom for rolling bubbles. Salt (pasta/veg water): 10g per 1L (~1 tbsp/quart) — seasons from the inside, not mandatory for technical perfection but recommended. Blanching shock bath: 4:1 ice-to-water, enough volume to re-chill food in under 60 sec. Ideal tool: wide, tall stockpot.
HEAT: Full rolling boil — 100°C/212°F at sea level, continuous large bubbles across the whole pot, not just the center. Adding food (especially cold) drops the boil temporarily — expected; keep the lid off/cracked to help it return faster. Don't overload the water beyond what it can support at a rolling boil (classic pasta mistake → gummy, uneven). Audio/visual: vigorous continuous surface agitation with steam escaping; a quiet boil under a lid means it's stalled.
DONENESS: Minimal color change is the point — this isn't for browning. Pasta: slight resistance at the center when bitten (al dente). Potatoes for mashing: slide off a knife tip with zero resistance. Salt the water before food goes in, always — salting after only seasons the surface. Acid (vinegar in poaching water, lemon on finished veg) is a finishing move, not a boiling-stage one — it toughens some proteins if added too early.
PITFALLS: (1) Unsalted water → bland food no later seasoning fully fixes — fix: oversalt the sauce/dressing slightly to compensate. (2) Overcrowded pot → mushy/uneven — fix: pull excess, let water return to a full boil, return food in batches. (3) Overcooking (soft/blown-out) — fix: shock immediately in ice water to halt carryover.
INGREDIENT FLEX: Eggs and stock proteins start in cold water (easier peel/even cook; better extraction, clearer stock). Poaching fish/shrimp needs a bare simmer, not a true boil (rolling boil toughens/shreds delicate proteins). Dense/root veg (potatoes, carrots) start in cold water, brought up together, so outside doesn't overcook before center is done. Leafy/watery veg (spinach, green beans) added to already-boiling water, cooked briefly (30–90 sec), shocked immediately.
''',

  'simmering': '''
TECHNIQUE: Simmering
RATIOS: Liquid-to-food: ½–¾ up the food for braising/poaching in liquid, or fully submerged for pure poaching — lower liquid volumes than boiling. Reduction math: roughly 25–30% volume loss per hour of active uncovered simmering — plan liquid volume for a specific final yield. Ideal tool: heavy-bottomed pot/Dutch oven for even retention; smaller saucepan for sauces/single-portion poaching.
HEAT: 85–96°C/185–205°F — small, gentle, lazy bubbles breaking intermittently, not a rolling boil. This is a maintenance state, not a starting one — bring to a boil first, then drop heat to hold this gentler bubble. Food should stay mostly submerged/covered for even cooking. Audio/visual: soft occasional "blip" bubbles, wisps of steam — silent/still means you've dropped into a poach/hold; rolling hard means you've overshot into a boil.
DONENESS: Gradual, gentle color change — braises deepen slowly over hours; poached items barely change color at all (no Maillard here). Braised proteins should be fork-tender, pulling apart with almost no resistance; poached proteins just-set, still yielding gently. Build aromatics and salt into the liquid early — slow-extraction technique, flavor has time to develop. Wine/vinegar/tomato acid added early helps break down collagen in braises (a real chemical assist); a final bright acid hit balances richness.
PITFALLS: (1) Letting it roll into a full boil → toughens proteins, breaks emulsions, clouds stock — fix: drop heat immediately, let it settle. (2) Not enough liquid, food scorches/dries — fix: top up with HOT (not cold) liquid to avoid a temp crash, stir gently. (3) Pulling proteins too early — tough braise — fix: return to low simmer, give it more time; collagen breakdown can't be rushed.
INGREDIENT FLEX: Dense proteins (beef chuck, pork shoulder, chicken thighs) thrive on long low simmer; tofu can simmer briefly in broth to absorb flavor without breaking down. Delicate proteins (fish, poached eggs) very short window, 3–6 min for most fish fillets, pull the moment they turn opaque. Dense/root veg (potatoes, carrots in stews) hold up well to long simmers, add early. Leafy/watery veg (spinach, zucchini) add in the last 5–10 min or they turn to mush.
''',

  'steaming': '''
TECHNIQUE: Steaming
RATIOS: Water level 2.5–5cm/1–2in below the steamer basket — enough for sustained steam without boiling dry. Food pieces need small gaps for steam circulation — don't pack the basket solid. Ideal tool: bamboo steamer over a wok, or a metal collapsible basket in a lidded pot. Multi-tier bamboo lets proteins and veg cook simultaneously without flavor transfer if separated. No steamer? A heatproof plate on a foil ball/upturned ramekin in a covered pot with shallow water works. Layering sliced citrus/aromatics/alliums on the base infuses the vapor with seasoning.
HEAT: Water at a steady boil generating continuous, visible steam — the steam itself is the cooking medium, needs to be constant. Opening the lid to check releases significant heat and adds cook time — resist checking early/often. Overcrowded baskets block circulation, same principle as pan-crowding, just with vapor. Audio/visual: steady stream of visible steam escaping the lid edges; thin inconsistent wisps mean water level too low or heat too weak.
DONENESS: Vegetables should brighten (not dull) — the classic sign steam is working correctly, not stewing them. Fish should flake easily with light pressure; dumplings/buns should spring back gently; vegetables should have slight give but not be limp. Steaming adds no salt itself — marinate/season before, or serve with a sauce/dip. Bright, punchy finishing sauces (ginger-scallion oil, chili-vinegar, citrus soy) are almost mandatory — steaming is a blank canvas.
PITFALLS: (1) Water boils dry mid-cook → scorched pot, ruined food — fix: always check water level before anything over 15 min, keep hot water ready to top up. (2) Overcrowded basket → uneven doneness — fix: remove excess, steam in batches, split across tiers with gaps. (3) Condensation drips pooling (soggy dumplings/buns) — fix: line the basket with cabbage leaves, parchment, or a light cloth.
INGREDIENT FLEX: Dense proteins (chicken pieces, tofu) — slower than pan methods but good for retaining moisture in lean cuts. Delicate proteins (fish, shellfish, eggs in a bowl) — this is where steaming shines, gentle heat preserves texture better than almost any other method. Dense/root veg steam longer (12–20 min depending on cut) since there's no direct water contact. Leafy/watery veg very short steam time (2–4 min), they turn mushy quickly.
''',

  // ---------------------------------------------------------------------
  // DRY & COMBINATION HEAT
  // ---------------------------------------------------------------------

  'roasting': '''
TECHNIQUE: Roasting
RATIOS: 1–2 tbsp oil/fat per 450g/1lb — enough to conduct heat and aid browning, not enough to fry. Minimum 2.5cm/1in gap between pieces on the tray — the single most-violated rule in home roasting. Food should cover no more than 70% of tray surface. Rest large roasts 10 min per 500g/1lb before carving. Ideal tool: rimmed sheet pan for veg/smaller cuts; roasting pan with a rack for whole birds/large roasts so fat drips away instead of frying the bottom. No rack? A bed of chopped vegetables under the protein elevates it out of its own fat.
HEAT: Oven fully preheated before food goes in, always, no exceptions. Fan-assisted increases caramelization but can dry things out — start with fan for the Maillard reaction, then switch to top-bottom heat once browned for proteins. Typical range: 190–230°C/375–450°F for vegetables/smaller cuts; 160–180°C/325–350°F for large roasts needing gentle, even penetration. A cold tray dropped into a hot oven drops oven temp temporarily — normal, don't crank heat higher to compensate. Check at the halfway mark: even golden color across all pieces = good spacing/airflow; pale wet spots = overcrowding or a hot spot.
DONENESS: Deep golden-brown, caramelized edges IS the flavor — don't pull the moment it "looks done," push for real color. Vegetables: slight caramelized crunch at the edge, tender center. Proteins: thermometer is the only honest test — poultry 74°C/165°F, beef/lamb medium 57–60°C/135–140°F (carryover adds a few more degrees). Chicken thighs (no breast) can go over 80°C for more tenderness than the safe minimum; breast should stay at the safe temp or it dries out. Salt proteins well ahead (dry brine, 40+ min or overnight) for crust/penetration; salt vegetables right before roasting so they don't weep water. Finishing acid (lemon, vinaigrette, deglazed pan drippings) added after resting, not before roasting.
PITFALLS: (1) Overcrowded tray → steamed, pale — fix: split across two trays/batches, no in-oven fix once steaming. (2) Cutting a rested-too-little roast → juices flood the board — fix: spoon the lost juice back over the sliced meat. (3) Underseasoned interior (salt only on the surface) — fix: finish with a compound butter or pan sauce to layer seasoning back in.
INGREDIENT FLEX: Dense proteins (whole chicken, pork loin, beef roasts) benefit from a rack and moderate-low heat for even doneness. Delicate proteins (fish) roast hot and fast (200°C+/400°F+), short window, easy to overcook. Dense/root veg (potatoes, carrots, squash) roast most forgivingly — cut uniformly, toss well in oil. Leafy/watery veg (zucchini, mushrooms) roast hot and fast in a single layer, or pre-salt/drain excess water first. Mixed cooking times on one tray (e.g. potatoes + zucchini): cut the slower item smaller, or start it first and add the rest halfway through — a good hands-off compensation strategy. Cast iron skillet works for stovetop-sear-then-oven-finish in one pan.
''',

  'braising': '''
TECHNIQUE: Braising
RATIOS: Liquid comes ⅓ to ½ up the side of the protein — braising is NOT submersion (that's stewing/boiling), it's combination sear + partial-liquid slow cook. Sear-to-braise time: 10–15% of total cook time for searing (building fond/color), 85–90% for the low, slow liquid cook. Classic mirepoix: 2 parts onion : 1 part carrot : 1 part celery, by volume. Ideal tool: Dutch oven (enameled cast iron ideal) — goes stovetop-to-oven seamlessly. No tight lid? Cover with foil under it to reduce evaporation.
HEAT: Sear phase hot (200°C+/400°F+ pan surface, as per Searing/Sautéing specs); braise phase drops to a bare simmer, 140–160°C/285–325°F oven or lowest stovetop simmer. The pot needs to fully return to temperature after liquid is added and before it goes in the oven — bring to a simmer on the stovetop first, then transfer. Don't overcrowd the sear stage — sear in batches, then combine for the braise phase. Liquid should show only occasional slow bubbles at the surface during braise — a rolling boil toughens the protein you're trying to tenderize.
DONENESS: Deep mahogany-brown crust from the sear stage; deep rich color in the finished braising liquid from reduction and fond. The definitive fork-tender test — a fork should slide in and the meat pull apart with almost no resistance; if there's resistance, it's not done regardless of clock time. Salt the protein before searing; build salt and acid into the braising liquid early so it has time to penetrate over the long cook. Wine/tomato/vinegar acid isn't just flavor — it helps break down connective tissue. Finish with a fresh herb or bright vinegar note to cut richness.
PITFALLS: (1) Skipping the sear → flat flavor, no fond depth — no recovering mid-braise, but a splash of soy sauce/miso/Worcestershire can patch in some umami. (2) Liquid at a hard boil the whole time → tough, dry meat despite hours of cooking — fix: drop heat immediately; even already-tough meat can sometimes still recover with extended low simmering (collagen breakdown continues). (3) Not enough liquid, braise dries and scorches — fix: top up with hot liquid immediately, scrape any scorched bits away so bitterness doesn't spread.
INGREDIENT FLEX: Dense proteins (beef short rib, pork shoulder, lamb shank) — the classic category, tough cuts with connective tissue that need time to break down. Delicate proteins (fish, eggs) are NOT a natural fit — skip or use a much shorter, gentler version (poaching instead). Dense/root veg (carrots, potatoes, celery root) braise beautifully alongside proteins, add at the start. Leafy/watery veg — mushrooms hold up well added early; spinach/zucchini only in the last 10–15 min. A slow cooker can approximate the braise phase (not the sear) if no Dutch oven is available — sear separately first, then transfer.
''',

  'grilling': '''
TECHNIQUE: Grilling
RATIOS: Two-zone setup: roughly 60% direct high heat / 40% indirect lower heat — the single most important grilling setup skill. Oil: light coating on the food itself (not the grates), 1–2 tsp per portion, prevents sticking without flare-ups. Basic marinade: 3 parts oil : 1 part acid : seasoning, minimum 30 min for thin cuts, up to 24hrs for tougher/larger cuts. Ideal tool: gas/charcoal grill with a lid (for indirect zone control); ridged cast iron grill pan as an indoor substitute.
HEAT: Direct zone hot enough that a hand held 12cm/5in above the grate lasts only 2–3 sec; indirect zone, 5–7 sec. Cold food straight from the fridge sears less evenly — bring proteins closer to room temp (20–30 min out) when time allows. Leave gaps between pieces on the grate, same principle as pan techniques. Audio/visual: confident sizzle and light char smoke on contact (billowing black smoke signals a flare-up from dripping fat).
DONENESS: Distinct cross-hatch/linear char marks from direct contact, deep golden-to-charred at contact points, contrasted with the food's natural color between marks. Touch test (relative firmness compared to different hand positions) is the classic on-the-fly check, backed by a thermometer for anything thick or bone-in. Internal: poultry 74°C/165°F, beef/lamb medium 57–60°C/135–140°F, pork 63°C/145°F, with a few minutes rest after pulling. Salt proteins ahead (dry brine) for the best crust; wet marinades should be patted mostly dry before the grill or you'll steam instead of char. Finish with citrus or a vinegar-based sauce (chimichurri, salsa verde) after grilling, not during.
PITFALLS: (1) Flare-ups from dripping fat → burnt, acrid exterior — fix: move food to the indirect zone immediately until flames die down, then return. (2) Flipping too often → poor char, sticking — fix: leave food alone until it releases naturally. (3) No two-zone setup → everything either burns outside or stays raw inside — fix: physically move food from hot to cool zone mid-cook to finish through without burning further.
INGREDIENT FLEX: Dense proteins (steak, chicken pieces, pork chops, firm tofu) — sear on direct, finish on indirect for thicker cuts. Delicate proteins (fish, shrimp) — oil the grates well or use a fish basket/foil packet, they stick and fall apart easily on open grates. Dense/root veg (potatoes, carrots) par-cook before grilling (boil/microwave) — raw dense veg won't cook through in a typical grilling window. Leafy/watery veg (zucchini, mushrooms) grill hot and fast on direct, watch closely as they release liquid quickly. A cast iron grill pan indoors replicates direct-zone char reasonably well, though not live-fire smoke flavor.
''',

  // ---------------------------------------------------------------------
  // AROMATIC & FLAVOR BUILDING
  // ---------------------------------------------------------------------

  'sweating_aromatics': '''
TECHNIQUE: Aromatic Base Building (Sweating & Blooming)
RATIOS: Classic Western mirepoix: 2 parts onion : 1 part carrot : 1 part celery. Cajun/Creole "holy trinity": equal parts onion, bell pepper, celery. Asian base: garlic + ginger roughly 1:1, minced fine, sometimes with scallion whites. Latin sofrito: onion, garlic, bell pepper, tomato — onion always the largest share. Oil for sweating: 2–3 tbsp per standard batch. Spice blooming: whole/ground spices in 1–2 tbsp hot oil for 30–60 sec before liquid or other ingredients. Ideal tool: wide, heavy-bottomed pot for sweating; small skillet for quick spice blooming.
HEAT: Sweating target 120–150°C/250–300°F, low-medium — the goal is softening and releasing flavor, NOT browning (the most common execution error in home cooking is sweating at browning temps). Spice blooming: medium heat, oil shimmering not smoking — spices go from fragrant to burnt in seconds at high heat. Aromatics release moisture as they cook — that's the cue sweating is working, don't rush past it by cranking heat. More forgiving of volume than searing since low heat is the whole point. Audio/visual (sweating): gentle quiet sizzle, visible steam, glistening softening vegetables — no color change is the goal. Audio/visual (blooming): fragrant within 20–30 sec, oil takes on the spice's color — pull the moment you smell it.
DONENESS: Onions should turn translucent and glassy, not browned (browning is a different technique — caramelizing, see below). Ground spices deepen slightly, oil around them tints — that shift is the flavor compound release. Sweated vegetables should be soft enough to crush between fingers once cool. A small pinch of salt at the very start of sweating helps draw moisture and speeds the process — different from the "salt at the end" rule elsewhere. Acid is generally NOT part of this stage — comes later once the base is built into a full dish.
PITFALLS: (1) Heat too high → browned/caramelized aromatics when a neutral base was wanted — no reversing, either lean into the new flavor direction or restart at lower heat. (2) Burnt garlic (added too early alongside slower aromatics) → bitter flavor spreading through the whole dish — fix: remove from heat immediately, pick out isolated dark bits if possible, otherwise restart. (3) Burnt spices from blooming too long/hot — fix: pull off heat the instant you smell burning (not just browning); start the bloom over in fresh oil if needed.
INGREDIENT FLEX: Aromatics typically built before proteins are added to braises/stews, or after searing (same pan, using rendered fat). Fish/seafood aromatic bases lean lighter and more fragrant (ginger, scallion, garlic) rather than heavy mirepoix, often built quickly at the end. Carrots/celery are aromatic-base staples themselves — their role here is flavor-building, not the final vegetable component. Leafy/watery veg not typically part of the base itself, added after since they cook much faster. General order-of-addition rule: onion before garlic, garlic before ginger, ground spices before delicate fresh herbs — each has a different burn threshold.
''',

  'caramelization': '''
TECHNIQUE: Caramelization
RATIOS: Onion ratio for deep caramelization: expect roughly 6–8 cups raw sliced onion to reduce to about 1–1.5 cups fully caramelized — huge volume loss is normal. Oil/fat: 1–2 tbsp per batch, topped up if the pan dries out. Optional sugar-assist: a pinch (½–1 tsp) can speed browning, though it flattens complexity vs. patient natural caramelization. Ideal tool: wide, heavy-bottomed pan (stainless lets you see fond color develop; cast iron retains heat well for the long process).
HEAT: Low-medium, patient and steady — true caramelization takes 35–45+ min for onions; anything rushed at high heat is browning/charring, not true caramelization. Stir occasionally, not constantly — let fond build on the pan bottom between stirs, deglaze it back in with a splash of water if it starts sticking too hard. A full pan of raw onion looks unmanageable at first — volume drops dramatically as moisture cooks out over the first 10–15 min.
DONENESS: Color progression is the doneness map — translucent (5 min) → soft pale gold (15 min) → light amber (25 min) → deep mahogany-brown (35–45+ min); patience through each stage builds real depth. Fully caramelized onions should be jammy, soft, almost spreadable — no crunch or structure left. A pinch of salt early helps draw moisture and speed the process; final seasoning happens at the end since flavor concentrates dramatically. A small splash of vinegar or wine at the very end balances the intense sweetness — one of the few times acid is almost mandatory.
PITFALLS: (1) Heat too high, rushing → burnt, bitter, acrid instead of sweet — no recovery, lower heat and restart with a fresh batch, patience is the only real technique here. (2) Not stirring/deglazing stuck fond → scorched bits through the batch — fix: deglaze lightly-stuck fond with a splash of water; remove burnt bits if scorched black. (3) Giving up too early (10–15 min) and calling it "caramelized" — that's actually sautéed/softened onion; relabel it, and if true caramelization is needed, it needs the full time.
INGREDIENT FLEX: Primarily an onion technique, but the same low-slow-patient principle applies to shallots, leeks, and some root vegetables (carrots) for a similar sweet, deep transformation. A slow cooker on low can caramelize onions hands-off over several hours, trading active attention for total time.
''',

  'toasting_blooming': '''
TECHNIQUE: Toasting & Blooming Spices/Nuts
RATIOS: Dry-toast (whole spices, nuts): no oil, direct dry heat in a skillet, tossed/stirred constantly. Oil-bloom (ground spices, curry pastes): 1–2 tbsp oil per 1–2 tbsp spice, enough to fully submerge and hydrate ground particles. Ideal tool: small, dry skillet for toasting; same skillet with oil added for blooming.
HEAT: Medium heat, constant motion — this is a fast, attention-demanding technique, not a walk-away one. Nuts and spices have very low thermal mass — perfectly toasted to burnt happens in seconds, so heat control and attentiveness matter more here than almost any other technique. Listen for light popping/crackling from whole spices (mustard seed, cumin seed) as they toast — that's the signal they're releasing their oils.
DONENESS: Light golden for nuts, slightly darkened and glossy for whole spices — subtle shifts, easy to miss if not watching closely. Smell is the clearest doneness signal in this entire technique — a rich, nutty, fragrant aroma means it's ready; pull immediately, don't wait for more visual color. Toasted nuts should feel warm and slightly firm, not soft (soft after cooling usually means underdone).
PITFALLS: (1) Walking away, even briefly → burnt batch — no recovery, burnt nuts/spices taste acrid throughout; always start fresh and stay at the stove. (2) Pan too hot → outside toasts before inside warms through — fix: lower heat immediately, shake/stir more frequently. (3) Leaving toasted nuts/spices in the hot pan after removing from heat — fix: transfer to a cool plate/bowl immediately, residual pan heat keeps cooking them.
INGREDIENT FLEX: Nuts (almonds, walnuts, pine nuts, cashews) all follow the same dry-toast principle, though thinner/smaller nuts (pine nuts) toast faster and need closer attention. Whole spices (cumin, coriander, mustard seed, fennel seed) all benefit from a quick dry toast before grinding for significantly more aromatic depth than pre-ground versions. Ground spices/pastes bloom better in oil than dry-toasting, since the goal is infusing the cooking fat itself before other ingredients are added.
''',
};