// Renders Cook Mode with the REAL recipe generated by
// `profile_wiring_probe.dart` (which writes build/probe_recipe.json).
//
// Split from that probe because the two cannot share a process: widget tests
// need TestWidgetsFlutterBinding, and that binding fails every real HTTP
// request with a 400. So one process generates, this one renders.
//
// Run (in order):
//   flutter test test/manual/profile_wiring_probe.dart
//   flutter test test/manual/cookmode_render_probe.dart

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:optimeal/screens/one_pan_cooking_roadmap_screen.dart';
import 'package:optimeal/services/chef_recipe_parser.dart';
import 'package:optimeal/services/user_profile_service.dart';
import 'package:optimeal/state/ingredient_prep_controller.dart';
import 'package:optimeal/state/user_profile_controller.dart';
import 'package:optimeal/widgets/step_timer_pill.dart';

void _log(Object? o) {
  // ignore: avoid_print
  print(o);
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  setUp(() => SharedPreferences.setMockInitialValues({}));

  testWidgets('a real generated recipe, driven to Cook Mode', (tester) async {
    final file = File('build/probe_recipe.json');
    if (!file.existsSync()) {
      _log('RENDER: build/probe_recipe.json missing — run the wiring probe first');
      return;
    }

    final recipe = await parseChefRecipeJson(
      raw: file.readAsStringSync(),
      portions: 5,
      fallbackTitle: 'Probe recipe',
      surface: ChefRecipeSurface.fridgeClearer,
      useGenericFallbacks: false,
      readDescription: true,
    );
    if (recipe == null) {
      _log('RENDER: parse failed');
      return;
    }

    final profile = UserProfileController(UserProfileService());
    await tester.pumpWidget(MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => IngredientPrepController()),
        ChangeNotifierProvider.value(value: profile),
      ],
      child: MaterialApp(home: OnePanCookingRoadmapScreen(recipe: recipe)),
    ));
    await tester.pump();

    _log('RENDER recipe: ${recipe.title}');
    _log('RENDER steps:  ${recipe.steps.length} generated');

    await tester.tap(find.text('Start Cooking').last);
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 400));

    // Step 1 is the mise read — no timer at all.
    _log('RENDER step 1 timer pills: '
        '${find.byType(StepTimerPill).evaluate().length} (expect 0 — mise)');

    await tester.tap(find.text("Board's clear — heat goes on"));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 400));

    final pill = tester.widget<StepTimerPill>(find.byType(StepTimerPill));
    _log('RENDER step 2 timer state: ${pill.state.name} '
        '(expect idle) · shows ${pill.remaining.inMinutes} min');

    // And it stays idle: wall clock advances, nothing counts.
    await tester.pump(const Duration(seconds: 5));
    final after = tester.widget<StepTimerPill>(find.byType(StepTimerPill));
    _log('RENDER after 5s:        ${after.state.name} '
        '· still ${after.remaining.inMinutes} min');

    expect(after.state, StepTimerState.idle);

    await tester.pumpWidget(const SizedBox());
  });
}
