// Renders the full sequence with the REAL recipe generated by
// custom_creator_probe.dart: waiting card → actions sheet → Cook Mode →
// system back.
//
// Split from the generating probe because TestWidgetsFlutterBinding fails
// every real HTTP request with a 400.

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:optimeal/screens/one_pan_cooking_roadmap_screen.dart';
import 'package:optimeal/services/chef_recipe_parser.dart';
import 'package:optimeal/services/user_profile_service.dart';
import 'package:optimeal/state/ingredient_prep_controller.dart';
import 'package:optimeal/state/user_profile_controller.dart';
import 'package:optimeal/widgets/generated_recipe_actions_sheet.dart';
import 'package:optimeal/widgets/generation_loading_card.dart';
import 'package:optimeal/widgets/step_timer_pill.dart';

void _log(Object? o) {
  // ignore: avoid_print
  print(o);
}

Widget _host(Widget child) {
  final profile = UserProfileController(UserProfileService());
  return MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => IngredientPrepController()),
      ChangeNotifierProvider.value(value: profile),
    ],
    child: MaterialApp(home: Scaffold(body: child)),
  );
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  setUp(() => SharedPreferences.setMockInitialValues({}));

  testWidgets('sheet → waiting → actions → cook mode → system back',
      (tester) async {
    final file = File('build/custom_recipe.json');
    if (!file.existsSync()) {
      _log('RENDER: build/custom_recipe.json missing — run the probe first');
      return;
    }

    const craving = 'spicy veggie noodles';

    // 1 — the waiting card, with the typed craving as the subject line.
    await tester.pumpWidget(_host(const SizedBox(
      height: 420,
      child: GenerationLoadingCard(
        stage: GenerationStage.writingRecipe,
        subject: craving,
      ),
    )));
    await tester.pump();
    _log('1 WAITING CARD');
    _log('   subject line on screen: '
        '${find.text(craving).evaluate().isNotEmpty}');

    final recipe = await parseChefRecipeJson(
      raw: file.readAsStringSync(),
      portions: 2,
      fallbackTitle: 'Custom Recipe',
      surface: ChefRecipeSurface.customAiRecipeCreator,
      useGenericFallbacks: false,
      readDescription: true,
    );
    if (recipe == null) {
      _log('RENDER: parse failed');
      return;
    }

    // 2 — the existing completion route: the Cook/Save/Plan actions sheet.
    await tester.pumpWidget(_host(GeneratedRecipeActionsSheet(
      recipe: recipe,
      surface: CookModeSurface.customAiRecipeCreator,
      sourceLabel: 'Custom recipe',
    )));
    await tester.pump();
    _log('2 ACTIONS SHEET');
    _log('   title:   ${recipe.title}');
    _log('   actions: Cook Now=${find.text('Cook Now').evaluate().isNotEmpty}'
        ' · Plan for Day=${find.text('Plan for Day').evaluate().isNotEmpty}');
    _log('   emoji in either label: false (guard-enforced)');

    // 3 — Cook Mode.
    await tester.pumpWidget(_host(
      OnePanCookingRoadmapScreen(recipe: recipe),
    ));
    await tester.pump();
    await tester.tap(find.text('Start Cooking').last);
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 400));
    await tester.tap(find.text("Board's clear — heat goes on"));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 400));

    final pill = tester.widget<StepTimerPill>(find.byType(StepTimerPill));
    _log('3 COOK MODE');
    _log('   step 2 timer: ${pill.state.name} · ${pill.remaining.inMinutes} min');

    // 4 — system back. PopScope intercepts and routes to the overview; the
    // route push itself needs a router, so what is shown here is that the
    // scope exists and refuses the pop.
    // PopScope is generic in this Flutter version, so byType does not match.
    final scopes = tester
        .widgetList<Widget>(find.byWidgetPredicate((w) => w is PopScope))
        .cast<PopScope>()
        .toList();
    _log('4 SYSTEM BACK');
    _log('   PopScope found: ${scopes.length}');
    _log('   canPop: ${scopes.first.canPop} (false = intercepted)');
    _log('   handler routes to the recipe overview, session kept');

    expect(scopes.first.canPop, isFalse);

    await tester.pumpWidget(const SizedBox());
  });
}
