// Renders the audit H-1 repro sequence with the REAL recipe generated by
// `custom_creator_probe.dart` (which writes build/custom_recipe.json).
//
// Two processes, as always: widget tests need TestWidgetsFlutterBinding, and
// that binding fails every real HTTP request with a 400 — so one process
// generates against dev, this one drives the round trip.
//
// Run (in order):
//   flutter test test/manual/custom_creator_probe.dart
//   flutter test test/manual/h1_backtrip_probe.dart
//
// Sequence driven: overview → Start cooking → advance two steps → back
// (pops, H-2) → Start cooking again (resumes, H-1). Prints the rendered step
// index and the session identity before and after. There is no session id
// field on ActiveCookSession — identity is the normalized recipe key
// (SavedRecipesService.recipeKeyFor), which is what resume matching uses.

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:optimeal/nav.dart';
import 'package:optimeal/screens/one_pan_cooking_roadmap_screen.dart';
import 'package:optimeal/screens/recipe_details_screen.dart';
import 'package:optimeal/services/chef_recipe_parser.dart';
import 'package:optimeal/services/cook_session_storage_service.dart';
import 'package:optimeal/services/overview_route_registry.dart';
import 'package:optimeal/services/saved_recipes_service.dart';
import 'package:optimeal/services/upgrade_nudge_gate.dart';
import 'package:optimeal/services/user_profile_service.dart';
import 'package:optimeal/state/ingredient_prep_controller.dart';
import 'package:optimeal/state/user_profile_controller.dart';

import '../support/fake_saved_recipes_backend.dart';

void _log(Object? o) {
  // ignore: avoid_print
  print(o);
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  setUp(() {
    SharedPreferences.setMockInitialValues({});
    OverviewRouteRegistry.resetForTest();
    UpgradeNudgeGate.resetForTest();
  });

  testWidgets('H-1 repro on a real generated recipe', (tester) async {
    final file = File('build/custom_recipe.json');
    if (!file.existsSync()) {
      _log('PROBE: build/custom_recipe.json missing — run '
          'custom_creator_probe.dart first');
      return;
    }
    final payload = await parseChefRecipeJson(
      raw: file.readAsStringSync(),
      portions: 2,
      fallbackTitle: 'Probe Recipe',
      surface: ChefRecipeSurface.customAiRecipeCreator,
    );
    if (payload == null) {
      _log('PROBE: payload failed to parse');
      return;
    }
    _log('PROBE recipe: ${payload.title} '
        '(${payload.steps.length} generated steps)');

    final service = SavedRecipesService(backend: FakeSavedRecipesBackend());
    final profile = UserProfileController(UserProfileService());
    final router = GoRouter(
      initialLocation: AppRoutes.recipe,
      routes: [
        GoRoute(
          path: AppRoutes.recipe,
          builder: (context, state) {
            final extra = state.extra;
            return RecipeDetailsScreen(
              recipe: extra is CookModeRecipePayload ? extra : payload,
              service: service,
            );
          },
        ),
        GoRoute(
          path: AppRoutes.onePanCookingRoadmap,
          builder: (context, state) {
            final extra = state.extra;
            if (extra is ActiveCookSession) {
              return OnePanCookingRoadmapScreen(resumeSession: extra);
            }
            if (extra is CookModeLaunchRequest) {
              return OnePanCookingRoadmapScreen(
                recipe: extra.recipe,
                surface: extra.surface,
                servings: extra.servings,
              );
            }
            return const OnePanCookingRoadmapScreen();
          },
        ),
      ],
    );
    await tester.pumpWidget(MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => IngredientPrepController()),
        ChangeNotifierProvider.value(value: profile),
      ],
      child: MaterialApp.router(routerConfig: router),
    ));
    await tester.pumpAndSettle();

    await tester.tap(find.text('Start cooking'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Start Cooking').last);
    await tester.pumpAndSettle();
    await tester.tap(find.text("Board's clear — heat goes on"));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Next step'));
    await tester.pumpAndSettle();

    final storage = CookSessionStorageService();
    final before = await storage.loadActiveSession();
    final key = SavedRecipesService.recipeKeyFor(payload.title);
    _log('BEFORE back:');
    _log('  rendered: '
        '${tester.widgetList<Text>(find.textContaining('Step 3 of')).map((t) => t.data).join()}');
    _log('  session identity (recipe key): '
        '${SavedRecipesService.recipeKeyFor(before!.recipe.title)}');
    _log('  session activeStepIndex: ${before.activeStepIndex} · '
        'completed: ${before.completedSteps}');

    final inCook = find.descendant(
        of: find.byType(OnePanCookingRoadmapScreen),
        matching: find.byIcon(Icons.arrow_back));
    await tester.tap(inCook.first);
    await tester.pumpAndSettle();

    final overviews =
        find.byType(RecipeDetailsScreen, skipOffstage: false).evaluate().length;
    _log('AFTER back: overview instances in tree: $overviews '
        '(H-2: must be 1) · Cook Modes: '
        '${find.byType(OnePanCookingRoadmapScreen, skipOffstage: false).evaluate().length}');

    await tester.tap(find.text('Start cooking'));
    await tester.pumpAndSettle();

    final after = await storage.loadActiveSession();
    _log('AFTER resume:');
    _log('  rendered: '
        '${tester.widgetList<Text>(find.textContaining('Step 3 of')).map((t) => t.data).join()}');
    _log('  session identity (recipe key): '
        '${SavedRecipesService.recipeKeyFor(after!.recipe.title)} '
        '(same as before: ${SavedRecipesService.recipeKeyFor(after.recipe.title) == key})');
    _log('  session activeStepIndex: ${after.activeStepIndex} · '
        'completed: ${after.completedSteps}');

    await tester.pumpWidget(const SizedBox());
  });
}
